### ISSUE TITLE
PvE lists contain PvP rolls

### ISSUE THREAD

**Issue by GabeClark99** [2Pillows/dim_wishlist_splitter#4]
Lists tagged exclusively for PvE still contain rolls for PvP. 

For example, [pve.txt](https://raw.githubusercontent.com/2Pillows/dim_wishlist_splitter/main/wishlists/pve.txt) contains panda's recommended PvP roll for Waking Vigil. This example seems to be an instance of mis-labelling on voltron's part, as it's tagged for PvE instead of PvP. 
![image](https://github.com/2Pillows/dim_wishlist_splitter/assets/54868591/f9e6e5fa-aba1-45a7-aa08-2c7724232cba)

Another example is YeezyGT's recommended PvP roll for Fugue-55, which only includes a singular tag: PvP. 
![image](https://github.com/2Pillows/dim_wishlist_splitter/assets/54868591/dcb899ce-724f-43f4-b21c-47fe4b5f74cf)

**Comment by 2Pillows** [comment]
Thank you for letting me know about this issue. I think I’ve fixed the problem, but if I missed something please let me know.

There are some occurrences of mislabeling with Voltron that my splitter may not be able to handle. I believe these can be resolved by submitting an issue to the Voltron repository.

The second issue was related to how the splitter defines valuable text, which is then converted into tags. Not every roll in Voltron has a "tag:" field, some have tags inside parentheses or brackets. For example, the second roll you showed had "PvE" mentioned in parentheses, so it was tagged as PvE.

> // Fugue-55 - [YeezyGT's WQ] (pvp)
> //notes: [YeezyGT's WQ] [MW: Handling / Range] "Fugue-55 (pronounced 'fyoog') has the normal options, then a couple of interesting ones, like being able to combo Steady Hands / Snapshot, reduced flinch with the Suros Synergy Origin Trait, and then **(more PvE-focused)**, Auto-Loading/Vorpal (which is actually the perfect pairing for the Verity's Brow Atheon build). Not too bad." tags:pvp

I’ve changed valuable text to only use "tags:" unless no "tags:" are present, in which case parentheses and brackets are used. Using the roll above as an example, the valuable text will now include [YeezyGT's WQ], (pvp), and "tags:pvp". Including [YeezyGT's WQ] and (pvp) is important since these sections may contain information like (backup roll) or other tags not typically defined by Voltron.

I hope this clarifies everything. Sorry for the inconvenience, and thanks again for letting me know.
